services:
  opencti-connector-aggregator:
    image: ghcr.io/mata-elang-stable/opencti-connector-aggregator:latest
    build:
      context: .
      target: event-aggregator
    restart: unless-stopped
    container_name: opencti-connector-aggregator
    env_file:
      - ./event-aggregator/.env
    command: ["-u", "kafka_consumer_sensor_event.py"]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 10s
      resources:
        limits:
          cpus: "0.2"
          memory: 256M

  opencti-connector-parser:
    image: ghcr.io/mata-elang-stable/opencti-connector-parser:latest
    build:
      context: .
      target: event-parser
    container_name: opencti-connector-parser
    env_file:
      - ./event-parser/.env
    restart: unless-stopped
    command: ["-u", "event_parser.py"]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 10s
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
